### ISSUE TITLE
Add dependabot configuration for updating dependencies versions

### ISSUE THREAD

**Issue by Flashky** [Flashky/advent-of-code-yyyy#8]
Currently under beta testing at advent-of-code-2023 repo:
https://github.com/Flashky/advent-of-code-2023/blob/master/.github/dependabot.yml

Documentation:
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

It can help keeping updated both ``pom.xml`` and GitHub actions:

For Maven:
```yaml
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
```

For GiHub actions the following can be used:
```yaml
- package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`. (You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.)
    directory: "/"
    schedule:
      interval: "weekly"
```
